name: star_wars
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3+1
  freezed_annotation: ^2.1.0
  go_router: ^3.1.1
  riverpod: ^1.0.3+1
  star_wars_ui:
    path: packages/star_wars_ui

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  json_serializable: ^6.3.1
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true

  #
