name: star_wars_ui
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flex_color_scheme: ^5.0.1
  flutter:
    sdk: flutter
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter_gen:
  output: lib/src/gen/

  integrations:
    flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: NewYork
      fonts:
        - asset: lib/src/typography/fonts/new_york/NewYork-Bold.ttf
        - asset: lib/src/typography/fonts/new_york/NewYork-SemiBold.ttf

    - family: Nunito
      fonts:
        - asset: lib/src/typography/fonts/nunito/Nunito-Black.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-Bold.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-ExtraBold.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-Light.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-Regular.ttf
        - asset: lib/src/typography/fonts/nunito/Nunito-SemiBold.ttf
